### ISSUE TITLE
Todo list after implementing session

### ISSUE THREAD

**Issue by ylee297** [joey-tang/Knowledge-Base#1]
1. 
- In ProfileController.sendMessageView,  we have to pass currently signed in user id to view
- get it from the controller in the view, use it to pass the id to the next controller like profile/{{userId}}/send
- by using the userId, redirect to the page message/list/userId/

2. In getMessage function in message model, the query string for getting messages have to be fixed to get the messages by currently logged in user.
3. In getTalkList function in message model, user_from_id and user_to_id should be changed from hard coding to using passed user_id

**Comment by joey-tang** [comment]
Resolved
